# Generated by Django 3.2.4 on 2021-06-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='correct_option_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
