# Generated by Django 3.2.4 on 2021-06-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_score_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
