# Generated by Django 3.2.4 on 2021-06-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_score_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(default='Quiz Title', max_length=1000),
            preserve_default=False,
        ),
    ]
